gem 'libxml-ruby'
require 'xml'

require File.dirname( __FILE__ ) + '/ooyala/version'
require File.dirname( __FILE__ ) + '/ooyala/service'
require File.dirname( __FILE__ ) + '/ooyala/request'
require File.dirname( __FILE__ ) + '/ooyala/response'
require File.dirname( __FILE__ ) + '/ooyala/parser'
require File.dirname( __FILE__ ) + '/ooyala/error'
require File.dirname( __FILE__ ) + '/ooyala/query'
require File.dirname( __FILE__ ) + '/ooyala/custom_metadata'
require File.dirname( __FILE__ ) + '/ooyala/attribute_update'
require File.dirname( __FILE__ ) + '/ooyala/thumbnail_query'
require File.dirname( __FILE__ ) + '/ooyala/client'