require 'base64'
require 'cgi'
require 'digest/sha2'
require 'net/http'
require 'rational'

gem 'nokogiri'
require 'nokogiri'

gem 'activesupport'
require 'active_support'

require File.dirname( __FILE__ ) + '/ooyala/version'
require File.dirname( __FILE__ ) + '/ooyala/service'
require File.dirname( __FILE__ ) + '/ooyala/request'
require File.dirname( __FILE__ ) + '/ooyala/response'
require File.dirname( __FILE__ ) + '/ooyala/response_parser'
require File.dirname( __FILE__ ) + '/ooyala/error'
require File.dirname( __FILE__ ) + '/ooyala/query'
require File.dirname( __FILE__ ) + '/ooyala/custom_metadata'
require File.dirname( __FILE__ ) + '/ooyala/attribute_update'
require File.dirname( __FILE__ ) + '/ooyala/thumbnail_query'
require File.dirname( __FILE__ ) + '/ooyala/client'