require 'base64'
require 'cgi'
require 'digest/sha2'
require 'net/http'
require 'rational'

gem 'nokogiri'
require 'nokogiri'

gem 'activesupport'
require 'active_support'

require File.dirname( __FILE__ ) + '/ooyala/parsing'
require File.dirname( __FILE__ ) + '/ooyala/formatting'
require File.dirname( __FILE__ ) + '/ooyala/version'
require File.dirname( __FILE__ ) + '/ooyala/error'
require File.dirname( __FILE__ ) + '/ooyala/request'
require File.dirname( __FILE__ ) + '/ooyala/response'
require File.dirname( __FILE__ ) + '/ooyala/query_request'
require File.dirname( __FILE__ ) + '/ooyala/query_response'
require File.dirname( __FILE__ ) + '/ooyala/custom_metadata_request'
require File.dirname( __FILE__ ) + '/ooyala/custom_metadata_response'
require File.dirname( __FILE__ ) + '/ooyala/attribute_update_request'
require File.dirname( __FILE__ ) + '/ooyala/attribute_update_response'
require File.dirname( __FILE__ ) + '/ooyala/thumbnail_query_request'
require File.dirname( __FILE__ ) + '/ooyala/thumbnail_query_response'
require File.dirname( __FILE__ ) + '/ooyala/query_iterator'
require File.dirname( __FILE__ ) + '/ooyala/query_pager'
require File.dirname( __FILE__ ) + '/ooyala/query_item'
require File.dirname( __FILE__ ) + '/ooyala/thumbnail'
require File.dirname( __FILE__ ) + '/ooyala/account'
require File.dirname( __FILE__ ) + '/ooyala/client'